### ISSUE TITLE
Over-representation analysis in addition to GSEA

### ISSUE THREAD

**Issue by grst** [nf-core/differentialabundance#101]
### Description of feature

As far as I can tell the differentialabundance pipeline currently performs gene set enrichment analysis using the `gsea-cli`. It would be great to *additionally* support gene set analysis using a simple over-representation test (ORA, aka Fisher's exact test) based on the differential gene expression results. 

ORA is very easy to compute and to interpret and has therefore been recommended in [Geistlinger et al's benchmark paper](https://academic.oup.com/bib/article/22/1/545/5722384#225533012). 

Another advantage of basing the results on the list of differentially expressed genes is that the GSEA cli does not seem to model covariates. By using the DE genes the results are automatically accounted for an arbitrary design specified to DESeq2. 

### Possible implementation
Using the [clusterProfiler](https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html) package, more specifically: 
 * https://yulab-smu.top/biomedical-knowledge-mining-book/enrichment-overview.html#ora-algorithm
 * [code snippet](https://github.com/icbi-lab/deseq2icbi/blob/28e54a75598d39b70090376daa0e9ddefee25363/runDESeq2_ICBI.R#L306-L356) we have previously been using for such an analysis. 

P.S. clusterProfiler also implements GSEA based on a ranked gene list derived from differential expression analysis. I expect this is both faster than the GSEA cli and (being based on the corresponding DE gene list) takes covariates into account.

**Comment by pinin4fjords** [comment]
Sure, I'm a little wary of the Fishers-based methods because of arbitrary thresholding and [methodological issues](https://academic.oup.com/bioinformatics/article/23/8/980/198511), but they remain popular, so I'd support having one here. You're correct on the covariates of course- I actually really like the limma-hosted methods (romer(), piano() and so on) for that reason (though they're easier to integrate with edgeR than I suspect they would be for DESeq2). I do also have [a plan](https://github.com/nf-core/differentialabundance/issues/36) to use the preranked mode for GSEA, which if based on the estimated fold changes from modelling might allow some consideration of covariates. 

For consistency with how we're doing things so far in the workflow, we'd need a non-local clusterProfiler module first. If you could look at how the output of the DESeq2 module is structured that will inform on how you might structure the input channel(s).

I'm inclined to keep the GSEA implementation as-is, just because it's well established and recognised.

**Comment by pinin4fjords** [comment]
@WackerO 's [work on gprofiler2](https://github.com/nf-core/differentialabundance/pull/199) addresses the request for over-representation, so closing this for now. PRs implementing other methods welcome.
