### ISSUE TITLE
Make GTF optional

### ISSUE THREAD

**Issue by apeltzer** [nf-core/differentialabundance#46]
### Description of feature

At the moment the pipeline is written mostly for genomics context as it requires a GTF to be provided as mandatory input. This limits applications for other use cases where such a file might not be available. There could be potential solutions to this:

* Limit applications, e.g. do not run parts of the pipeline that use the GTF
* Allow different types of "annotation information", e.g. a plain TSV / similar that allows annotating features accordingly, thereby enabling use of the same functionality for other domains (proteomics, nanostring, ...)

**Comment by ggabernet** [comment]
That could be done with e.g. annotation packages as well for model species so that the user doesn't need to provide the annotation files (e.g. https://bioconductor.org/packages/release/data/annotation/html/org.Mm.eg.db.html)

**Comment by pinin4fjords** [comment]
> That could be done with e.g. annotation packages as well for model species so that the user doesn't need to provide the annotation files (e.g. https://bioconductor.org/packages/release/data/annotation/html/org.Mm.eg.db.html)

Just re-posting my response to this point from Slack for posterity:

"So, where a GTF has been involved in the upstream processing (which is the case for nf-core/rnaseq of course) I would personally always want to re-use the same file so no artifacts come out of mismatches due to Ensembl releases. For example, letting the RNA-seq workflow use iGenomes (which I think is Ensembl 84 or somesuch for mouse), and then using the current Ensembl Biomart (v 108 or similar) is bound to create problems.

That said, it will be pretty trivial to build modules that extract the annotation table from Bioconductor annotation packages.

I think there was talk of BioMart being retired at some point, but a module interface for that could be handy too."
